apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers: 
        - name: auth
          image: mohamedsalah112/auth
          ports:
            - containerPort: 4001
          env:
            - name: MONGO_URI
              value: 'mongodb://auth-mongo-srv:27017/auth'  
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY 
            - name: SENDGRID_API_KEY
              valueFrom:
                secretKeyRef:
                  name: sendgrid-secret
                  key: SENDGRID_API_KEY
            - name: TOTP_SECRET
              valueFrom:
                secretKeyRef:
                  name: totp-secret
                  key: TOTP_SECRET
                  
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      port: 4001
      targetPort: 4001
      protocol: TCP

