name: deploy-auth

on:
  push:
    branches:
      - main
    paths:
      - 'adminstration_backend (1)/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u $USER_NAME -p $USER_PASSWORD
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
      - run: cd adminstration_backend (1) && docker build -t mohamedsalah112/adminstration .
      - run: docker push mohamedsalah112/adminstration
